package org.example.controllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.Button;
import javafx.stage.Stage;
import org.example.entities.Exercice;
import org.example.services.QuizService;

import java.io.IOException;

public class ExerciceDetailController {

    @FXML private Label typeLabel;
    @FXML private Label questionLabel;
    @FXML private Label answerLabel;
    @FXML private Label quizLabel;
    @FXML private Label diffLabel;
    @FXML private Label statusLabel;
    @FXML private Label aiLabel;

    private Exercice exercice;
    private final QuizService quizService = new QuizService();

    public void setExercice(Exercice ex) {
        this.exercice = ex;
        
        typeLabel.setText(ex.getType().toUpperCase().replace("_", " "));
        questionLabel.setText(ex.getQuestion());
        answerLabel.setText(ex.getCorrectAnswer());

        // Status
        if (ex.isEnabled()) {
            statusLabel.setText("Active");
            statusLabel.setStyle("-fx-background-color: rgba(34, 197, 94, 0.1); -fx-text-fill: #16a34a; -fx-padding: 4 12; -fx-background-radius: 20; -fx-font-weight: bold;");
        } else {
            statusLabel.setText("Inactive");
            statusLabel.setStyle("-fx-background-color: rgba(245, 158, 11, 0.1); -fx-text-fill: #b45309; -fx-padding: 4 12; -fx-background-radius: 20; -fx-font-weight: bold;");
        }

        // AI Generated
        if (ex.isAiGenerated()) {
            aiLabel.setText("🤖 Generated by AI");
            aiLabel.setStyle("-fx-text-fill: #8b5cf6; -fx-font-weight: bold;");
        } else {
            aiLabel.setText("Human Created");
        }

        // Quiz
        quizService.getAllQuizzes().stream()
            .filter(q -> q.getId() == ex.getQuizId())
            .findFirst()
            .ifPresentOrElse(
                q -> quizLabel.setText(q.getTitle()),
                () -> quizLabel.setText("No Linked Quiz")
            );

        // Difficulty
        StringBuilder stars = new StringBuilder();
        for (int i = 0; i < ex.getDifficulty(); i++) stars.append("⭐");
        for (int i = ex.getDifficulty(); i < 5; i++) stars.append("☆");
        diffLabel.setText(stars.toString());
    }

    @FXML
    private void goBack() {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/ExerciceView.fxml"));
            Parent root = loader.load();
            Stage stage = (Stage) questionLabel.getScene().getWindow();
            Scene scene = stage.getScene();
            scene.setRoot(root);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
