package org.example.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.HBox;
import javafx.scene.control.Label;
import javafx.stage.Stage;
import org.example.entities.Exercice;
import org.example.entities.Rating;
import org.example.service.QuizService;
import org.example.service.RatingService;
import org.example.util.UserSession;
import org.kordamp.ikonli.javafx.FontIcon;

import java.io.IOException;

public class ExerciceDetailController {

    @FXML private Label typeLabel;
    @FXML private Label questionLabel;
    @FXML private Label answerLabel;
    @FXML private Label quizLabel;
    @FXML private HBox diffContainer;
    @FXML private Label statusLabel;
    @FXML private Label aiLabel;
    @FXML private Label avgRatingLabel;
    @FXML private Label userRatingFeedback;
    @FXML private HBox ratingStarContainer;

    private Exercice exercice;
    private final QuizService quizService = new QuizService();
    private final RatingService ratingService = new RatingService();

    public void setExercice(Exercice ex) {
        this.exercice = ex;
        
        typeLabel.setText(ex.getType().toUpperCase().replace("_", " "));
        questionLabel.setText(ex.getQuestion());
        answerLabel.setText(ex.getCorrectAnswer());

        // Status
        if (ex.isEnabled()) {
            statusLabel.setText("Active");
            statusLabel.setStyle("-fx-background-color: rgba(34, 197, 94, 0.1); -fx-text-fill: #16a34a; -fx-padding: 4 12; -fx-background-radius: 20; -fx-font-weight: bold;");
        } else {
            statusLabel.setText("Inactive");
            statusLabel.setStyle("-fx-background-color: rgba(245, 158, 11, 0.1); -fx-text-fill: #b45309; -fx-padding: 4 12; -fx-background-radius: 20; -fx-font-weight: bold;");
        }

        // AI Generated
        if (ex.isAiGenerated()) {
            aiLabel.setText("🤖 Generated by AI");
            aiLabel.setStyle("-fx-text-fill: #8b5cf6; -fx-font-weight: bold;");
        } else {
            aiLabel.setText("Human Created");
        }

        // Quiz
        quizService.getAllQuizzes().stream()
            .filter(q -> q.getId() == ex.getQuizId())
            .findFirst()
            .ifPresentOrElse(
                q -> quizLabel.setText(q.getTitle()),
                () -> quizLabel.setText("No Linked Quiz")
            );

        // Difficulty
        diffContainer.getChildren().clear();
        for (int i = 0; i < 5; i++) {
            FontIcon star = new FontIcon("fas-star");
            star.setIconSize(16);
            if (i < ex.getDifficulty()) {
                star.setIconColor(javafx.scene.paint.Color.web("#f59e0b"));
            } else {
                star.setIconColor(javafx.scene.paint.Color.web("#cbd5e1"));
            }
            diffContainer.getChildren().add(star);
        }

        loadRatings();
    }

    private void loadRatings() {
        if (exercice == null) return;

        double avg = ratingService.getAverageRating(exercice.getId());
        avgRatingLabel.setText(String.format("%.1f", avg));

        if (UserSession.currentUser != null) {
            int userRating = ratingService.getUserRating(UserSession.currentUser.getId(), exercice.getId());
            updateStarUI(userRating);
            if (userRating > 0) {
                userRatingFeedback.setText("Your rating: " + userRating + "/5 (Click to update)");
            } else {
                userRatingFeedback.setText("You haven't rated this exercise yet.");
            }
        } else {
            userRatingFeedback.setText("Login to rate this exercise.");
            // Stars will be disabled by not adding click listeners or setting disable
        }
    }

    private void updateStarUI(int rating) {
        ratingStarContainer.getChildren().clear();
        for (int i = 0; i < 5; i++) {
            final int starValue = i + 1;
            FontIcon star = new FontIcon("fas-star");
            star.setIconSize(16);
            
            if (i < rating) {
                star.setIconColor(javafx.scene.paint.Color.web("#f59e0b"));
            } else {
                star.setIconColor(javafx.scene.paint.Color.web("#cbd5e1"));
            }
            
            javafx.scene.layout.StackPane wrapper = new javafx.scene.layout.StackPane(star);
            wrapper.setStyle("-fx-cursor: hand; -fx-padding: 5;");
            if (UserSession.currentUser != null) {
                wrapper.setOnMouseClicked(e -> submitRating(starValue));
            }
            
            ratingStarContainer.getChildren().add(wrapper);
        }
    }

    private void submitRating(int value) {
        if (UserSession.currentUser == null || exercice == null) return;

        Rating rating = new Rating(UserSession.currentUser.getId(), exercice.getId(), value);
        ratingService.addOrUpdateRating(rating);
        loadRatings();
    }


    @FXML
    private void goBack() {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/admin/ExerciceView.fxml"));
            Parent root = loader.load();
            Stage stage = (Stage) questionLabel.getScene().getWindow();
            Scene scene = stage.getScene();
            scene.setRoot(root);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
